name: CI - Backend Node.js
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

concurrency:
  group: ci-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # JOB 1: setup (instala dependências e cache)
  setup:
    name: Setup & Install
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js (matrix-friendly)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (backend)
        working-directory: backend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi